const productImages: Record<string, any> = {
  "s1-1": require("@/assets/products/s1-1.png"),
  "s1-2": require("@/assets/products/s1-2.png"),
  "s1-3": require("@/assets/products/s1-3.png"),
  "s1-4": require("@/assets/products/s1-4.png"),
  "s1-5": require("@/assets/products/s1-5.png"),
  "s2-1": require("@/assets/products/s2-1.png"),
  "s2-2": require("@/assets/products/s2-2.png"),
  "s2-3": require("@/assets/products/s2-3.png"),
  "s2-4": require("@/assets/products/s2-4.png"),
  "s3-1": require("@/assets/products/s3-1.png"),
  "s3-2": require("@/assets/products/s3-2.png"),
  "s3-3": require("@/assets/products/s3-3.png"),
  "s3-4": require("@/assets/products/s3-4.png"),
  "s3-5": require("@/assets/products/s3-5.png"),
  "s4-1": require("@/assets/products/s4-1.png"),
  "s4-2": require("@/assets/products/s4-2.png"),
  "s4-3": require("@/assets/products/s4-3.png"),
  "s4-4": require("@/assets/products/s4-4.png"),
  "s5-1": require("@/assets/products/s5-1.png"),
  "s5-2": require("@/assets/products/s5-2.png"),
  "s5-3": require("@/assets/products/s5-3.png"),
  "s5-4": require("@/assets/products/s5-4.png"),
  "s6-1": require("@/assets/products/s6-1.png"),
  "s6-2": require("@/assets/products/s6-2.png"),
  "s6-3": require("@/assets/products/s6-3.png"),
  "s6-4": require("@/assets/products/s6-4.png"),
  "s7-1": require("@/assets/products/s7-1.png"),
  "s7-2": require("@/assets/products/s7-2.png"),
  "s7-3": require("@/assets/products/s7-3.png"),
  "s7-4": require("@/assets/products/s7-4.png"),
  "s7-5": require("@/assets/products/s7-5.png"),
};

export default productImages;
