uploads = []
outputs = []

[[generated]]
id = "9UrYHziKzWn4cMSfkV52r"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "WLuZH9URG4QwG583-3vxX"
uri = "file://artifacts/mobile/assets/images/hero-banner.png"
type = "image"
title = "generated_image"

[[generated]]
id = "chw0zq5soVQHc5Zt3ya_2"
uri = "file://artifacts/mobile/assets/images/category-fantasy.png"
type = "image"
title = "generated_image"

[[generated]]
id = "mkPtYtkNRXwuS7ZDLGIuu"
uri = "file://artifacts/mobile/assets/images/category-anime.png"
type = "image"
title = "generated_image"

[[generated]]
id = "vfWBfCblYAe6qKCirBdiC"
uri = "file://artifacts/mobile/assets/products/s1-1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "53fpPW0GLRIGWY8BPp2zY"
uri = "file://artifacts/mobile/assets/products/s1-2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "DzdBT0XL8cIMExSQ44Usp"
uri = "file://artifacts/mobile/assets/products/s1-3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "GzP-a9i0KpgPHucgi1B4G"
uri = "file://artifacts/mobile/assets/products/s1-4.png"
type = "image"
title = "generated_image"

[[generated]]
id = "6majRBScerj8fsVKRnrEK"
uri = "file://artifacts/mobile/assets/products/s1-5.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Z353maooXX83VPK__5wag"
uri = "file://artifacts/mobile/assets/products/s2-1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "uaT9_sqo_5YLAdncR3ibf"
uri = "file://artifacts/mobile/assets/products/s2-2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "L3FvvCyT0dtJz9qJH3HBC"
uri = "file://artifacts/mobile/assets/products/s2-3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "JSwJt-nPgFBECkeVCysT6"
uri = "file://artifacts/mobile/assets/products/s2-4.png"
type = "image"
title = "generated_image"

[[generated]]
id = "7wM9gX6T2Abu61nbtgAQY"
uri = "file://artifacts/mobile/assets/products/s3-1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "X_1i4NGed9O2qURGkpIPH"
uri = "file://artifacts/mobile/assets/products/s3-2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "TY8QalsNvQEEEhVIiXVJG"
uri = "file://artifacts/mobile/assets/products/s3-3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "wykCBKYqSNzM2vTIqlh2z"
uri = "file://artifacts/mobile/assets/products/s3-4.png"
type = "image"
title = "generated_image"

[[generated]]
id = "sEqo4Izi_znNCJYqx03Fi"
uri = "file://artifacts/mobile/assets/products/s3-5.png"
type = "image"
title = "generated_image"

[[generated]]
id = "IKWuxKq-j3z1C17fejWe6"
uri = "file://artifacts/mobile/assets/products/s4-1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "fq87fN87KkJTXatyf1z1N"
uri = "file://artifacts/mobile/assets/products/s4-2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "UdtGAjPd3Nh-r5tVeJ907"
uri = "file://artifacts/mobile/assets/products/s4-3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "QEbVaU8x0Tr5qeDN0EjW8"
uri = "file://artifacts/mobile/assets/products/s4-4.png"
type = "image"
title = "generated_image"

[[generated]]
id = "aBdOHLIVQcnvUqli8APEz"
uri = "file://artifacts/mobile/assets/products/s5-1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ZNUqaP3np3TfRpXZBJras"
uri = "file://artifacts/mobile/assets/products/s5-2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "hf9zE-KDF0tvoADhxZJ3F"
uri = "file://artifacts/mobile/assets/products/s5-3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "nJn7Slf65VCz97lfDt2VX"
uri = "file://artifacts/mobile/assets/products/s5-4.png"
type = "image"
title = "generated_image"

[[generated]]
id = "WZmsEmaxRxxuOmA_mutju"
uri = "file://artifacts/mobile/assets/products/s6-1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "gKWQuM8rgHvS9fRhDwsla"
uri = "file://artifacts/mobile/assets/products/s6-2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "8U8VavxKKNW2MY1mF3fPO"
uri = "file://artifacts/mobile/assets/products/s6-3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "NGot5PDXwIuJ5V0XDqAcC"
uri = "file://artifacts/mobile/assets/products/s6-4.png"
type = "image"
title = "generated_image"

[[generated]]
id = "uOogV86Bmpv8HhUpQ8Xiv"
uri = "file://artifacts/mobile/assets/products/s7-1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "vw4y8Wwf3S7n75Zuai0YF"
uri = "file://artifacts/mobile/assets/products/s7-2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "0YMr8IZ6dPggLMwoNRkw1"
uri = "file://artifacts/mobile/assets/products/s7-3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "xRH5_A4b2v6tM3zHSzl8p"
uri = "file://artifacts/mobile/assets/products/s7-4.png"
type = "image"
title = "generated_image"

[[generated]]
id = "tqXtifqBm8bwP-tQEB_U3"
uri = "file://artifacts/mobile/assets/products/s7-5.png"
type = "image"
title = "generated_image"
